# SEO and site configuration
site_name: Community Lecture Archive
site_description: Archive of weekly lectures and monthly events with links to videos and resources
site_url: https://gamalmoneep.github.io/Quantum_ai/
site_author: Quantum Computing Community

# SEO keywords and meta
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GamalMoneep/Quantum_ai
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@yourchannel
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  version:
    provider: mike

# Performance and SEO optimizations
use_directory_urls: true
strict: true

# SEO plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true

# Additional theme features
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - header.autohide
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/logo.png

nav:
  - Home: index.md
  - Lectures:
      - Overview: lectures/index.md
      - "Week 1: Introduction to Quantum Computing": lectures/week-01.md
      - "Week 2: Quantum Algorithms": lectures/week-02.md
      - "Week 3: Quantum Machine Learning": lectures/week-03.md
  - Events:
      - Overview: events/index.md
      - "January 2024 Community Meetup": events/january-2024.md
  - "2025 Events":
      - Overview: 2025/index.md
      - "Hackathon": 2025/hackathon/index.md
      - "Summer School": 2025/summer-school/index.md
      - "Dry Run Hackathon": 2025/dry-run-hackathon/index.md
  - "Monthly Series":
      - Overview: monthly-series/index.md
  - "Quantum AI Lab":
      - Overview: quantum-ai-lab/index.md
  - Resources: resources/index.md
  - "Our Team": contributors/index.md

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - toc:
      permalink: true


