name: Update YouTube Playlists

on:
  # Run automatically every day at 6 AM UTC
  schedule:
    - cron: '0 6 * * *'
  
  # Allow manual triggering
  workflow_dispatch:
  
  # Run when changes are pushed to main/master
  push:
    branches: [ main, master ]
    paths:
      - 'scripts/update_playlists.py'
      - '.github/workflows/update-playlists.yml'

jobs:
  update-playlists:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml
    
    - name: Create scripts directory
      run: mkdir -p scripts
    
    - name: Run playlist update
      id: update
      run: |
        cd scripts
        python update_playlists.py
        echo "Changes made: $?"
      continue-on-error: true
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "Changed files:"
          git status --porcelain
        else
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        fi
    
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "🤖 Auto-update: New videos added from YouTube playlists
        
        - Updated Monthly Series episodes
        - Updated Quantum AI Lab episodes
        - Refreshed navigation and content
        
        Generated automatically by GitHub Actions"
        git push
    
    - name: Deploy to GitHub Pages
      if: steps.verify-changed-files.outputs.changes == 'true'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        enable_jekyll: false
        commit_message: "🚀 Deploy: Updated site with new videos"
    
    - name: Build MkDocs site
      run: |
        pip install mkdocs-material
        mkdocs build
    
    - name: Summary
      run: |
        if [ "${{ steps.verify-changed-files.outputs.changes }}" == "true" ]; then
          echo "✅ Playlist update completed with new videos!"
          echo "🚀 Site has been updated and deployed"
        else
          echo "✅ Playlist update completed - no new videos found"
          echo "📺 All playlists are up to date"
        fi

